stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01.py
    deps:
      - src/cnnClassifier/pipeline/stage_01.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/kidney-scan-images


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02.py
    deps:
      - src/cnnClassifier/pipeline/stage_02.py
      - config/config.yaml
      - src\cnnClassifier\components\prepare_base_model.py
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/cnnClassifier/pipeline/stage_03.py
    deps:
      - src/cnnClassifier/pipeline/stage_03.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-scan-images
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_04.py
    deps:
      - src/cnnClassifier/pipeline/stage_04.py
      - config/config.yaml
      - artifacts/data_ingestion/kidney-scan-images
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false